# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0006_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default='空', max_length=255)),
                ('max_member_nums', models.IntegerField(default=255)),
                ('admins', models.ManyToManyField(related_name='qqgroup_admins', to='web.UserProfile')),
                ('members', models.ManyToManyField(blank=True, null=True, to='web.UserProfile')),
            ],
        ),
    ]
