# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '贴子', 'verbose_name_plural': '贴子'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='thumbup',
            options={'verbose_name': '点赞', 'verbose_name_plural': '点赞'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '分组', 'verbose_name_plural': '分组'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '帐户信息表', 'verbose_name_plural': '帐户信息表'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='categroy',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='版块'),
        ),
        migrations.AlterField(
            model_name='thumbup',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Article', verbose_name='点赞'),
        ),
    ]
