# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171225_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='test', max_length=255, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
