# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171230_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_comment', to='web.Comment', verbose_name='回复评论'),
        ),
    ]
